apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: ticker-counter
  annotations:
    description: 'A demo for the ticker provider'
    wasmcloud.dev/authors: James Stockton
    wasmcloud.dev/source-url: https://github.com/jamesstocktonj1/ticker-provider/blob/main/example/wadm.yaml
    wasmcloud.dev/readme-md-url: https://github.com/jamesstocktonj1/ticker-provider/blob/main/example/README.md
    wasmcloud.dev/homepage: https://github.com/jamesstocktonj1/ticker-provider
spec:
  components:
    - name: counter
      type: component
      properties:
        image: file://./counter/build/ticker_counter_s.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        - type: link
          properties:
            target: valkey
            namespace: wasi
            package: keyvalue
            interfaces: [atomics, store]
            target_config:
              - name: valkey-url
                properties:
                  url: redis://127.0.0.1:6379
        - type: link
          properties:
            target: ticker
            namespace: jamesstocktonj1
            package: ticker
            interfaces: [task]
            target_config:
              - name: ticker-config
                properties:
                  type: interval
                  period: 10s
              # - name: cron-config
              #   properties:
              #     type: cron
              #     cron: "0 * * * * *"
              #     seconds: "true"
              # - name: startup-config
              #   properties:
              #     type: startup
              #     delay: 30s

    - name: ticker
      type: capability
      properties:
        # image: file://../build/wasmcloud-ticker-provider.par.gz
        image: ghcr.io/jamesstocktonj1/ticker-provider:main

    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.23.2
      traits:
        - type: link
          properties:
            target: counter
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source_config:
              - name: http-link
                properties:
                  address: 0.0.0.0:8080

    - name: valkey
      type: capability
      properties:
        image: ghcr.io/wasmcloud/keyvalue-redis:0.28.1
