name: Build Ticker Provider

on:
  push:
    paths-ignore:
      - .github/**
      - example/**
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build Workflow
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Install wash-cli
        uses: wasmCloud/common-actions/install-wash@main
      - name: Install wit-bindgen-wrpc
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: wrpc
      - name: Install wasm-tools
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: wasm-tools
          
      - name: Build Provider
        run: wash build
      - name: Publish Provider
        env:
          WASH_REG_USER: ${{ github.actor }}
          WASH_REG_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: wash push ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.tags || 'main' }} build/wasmcloud-ticker-provider.par.gz