name: Test Ticker Provider

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test Workflow
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Run Tests
        run: go test . -coverprofile=coverage
      - name: Report Coverage
        run: go tool cover -func=coverage