name: Publish Wit

on:
  push:
    paths:
      - wit/**
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    name: Wit Workflow
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Install wash-cli
        uses: wasmCloud/common-actions/install-wash@main

      - name: Build Wit
        run: wash wit build
      - name: Publish Wit
        env:
          WASH_REG_USER: ${{ github.actor }}
          WASH_REG_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: wash wit publish *.wasm --wit-registry ghcr.io